GFMICsystem/GFMICsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

GFMICsystem/users/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('error_404/', views.error_404, name='error_404'),
    path('forgot-pw/', views.forgot_pass, name="forgot_pass"),
    path('register/', views.register, name='register'),
    path('register_account/', views.register_account, name='register_account'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/', views.process_login, name='process_login'),
    path('about/', views.about, name='about'),
    path('gfmic-event/', views.home_event, name='home_event'),
    path('webinar/', views.webinar, name='webinar'),
    path('membership-conference/', views.membership_conference, name='membership_conference'),
    path('national-convention/', views.national_convention, name='national_convention'),
    path('faqs/', views.faqs, name='faqs'),

    path('', views.payment, name='payment'),
    path('membership/', views.membership, name='membership'),
    path('add_profile/', views.profile, name='profile'),

    path('add_membership/', views.add_membership, name='add_membership'),
    path('view_membership/', views.view_membership, name='view_membership'),
    path('approve_membership/', views.approve_membership, name='approve_membership'),
    path('disapprove_membership/', views.disapprove_membership, name='disapprove_membership'),
    path('home/', views.home, name='home'),

    path('events/', views.events, name='events'),
    path('event/', views.event, name='event'),
    path('add_event/', views.add_event, name='add_event'),
    path('event', views.add_event_picture, name='add_event_picture'),
    path('event_remove/', views.event_remove, name='event_remove'),
    path('event_approve/', views.event_approve, name='event_approve'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

GFMICsystem/users/models.py
from django.db import models
from datetime import datetime
import os, random
from django.utils.html import mark_safe
from django.utils import timezone
from django.urls import reverse


now = timezone.now()

def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr =''.join((random.choice(chars)) for x in range(5))
    _now = datetime.now()

    return 'proof_pic/{year}-{month}-{day}-{basename}-{randomstring}{ext}'.format(basename = basefilename, randomstring=randomstr, ext=file_extension, year=_now.strftime('%Y'), month=_now.strftime('%m'), day=_now.strftime('%d'))

def event_image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr =''.join((random.choice(chars)) for x in range(5))
    _now = datetime.now()

    return 'event_img/{year}-{month}-{day}-{basename}-{randomstring}{ext}'.format(basename = basefilename, randomstring=randomstr, ext=file_extension, year=_now.strftime('%Y'), month=_now.strftime('%m'), day=_now.strftime('%d'))


class Membership(models.Model):
    user_id = models.AutoField(primary_key=True)
    user_no = models.CharField(unique=True, max_length=15, verbose_name='User Number')
    user_email = models.EmailField(unique=True, max_length=200, verbose_name='Email Address')
    user_password = models.CharField(max_length=16, verbose_name="Password")
    user_sub = models.CharField(max_length=16, verbose_name='Subscription', default="GUEST")
    user_status = models.CharField(max_length=16, verbose_name='Status', default="ACTIVE")
    user_application = models.CharField(max_length=16, verbose_name='User Application', null = True)
    user_pmode = models.CharField(max_length=16, verbose_name='User Payment', null = True)
    user_amount = models.IntegerField(null=True)
    user_validity = models.DateTimeField(max_length=50, null=True)
    user_expire = models.DateTimeField(max_length=50, null=True)
    user_lname = models.CharField(max_length=50, verbose_name='Last Name', null = True)
    user_fname = models.CharField(max_length=50, verbose_name='First Name', null = True)
    user_mname = models.CharField(max_length=50, verbose_name='Middle Name', null = True)
    user_sname = models.CharField(max_length=50,  null=True, verbose_name='Suffix Name')
    user_mobile = models.BigIntegerField(null=True, verbose_name='Mobile Number')
    user_file = models.FileField(upload_to=image_path, blank=True, null=True)
    user_dateupdated = models.DateTimeField(default=now)
    user_datecreated = models.DateTimeField(default=now)
    user_address = models.CharField(max_length=50, verbose_name='Address', null=True)
    user_agency = models.CharField(max_length=50, verbose_name='Agency', null=True)
    user_post = models.CharField(max_length=50, verbose_name='Educational', null=True)
    user_school = models.CharField(max_length=50, verbose_name='School Name', null=True)

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width = "50" height="50" />'%(self.user_file))

    def __str__(self):
        return self.user_id

class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    event_no = models.CharField(unique=True, max_length=15, verbose_name='Event Number')
    event_title = models.CharField(max_length=200, verbose_name='Event Title')
    event_associate = models.ForeignKey(Membership, on_delete=models.CASCADE)
    event_desc = models.CharField(max_length=200, verbose_name='Event Descriptions')
    event_time = models.CharField(max_length=20, verbose_name='Event Time')
    event_date = models.DateTimeField()
    event_evaluate = models.CharField(max_length=200, verbose_name='Evaluate')
    event_category = models.CharField(max_length=200, verbose_name='Event Category')
    event_image = models.FileField(upload_to=event_image_path)
    event_speaker = models.CharField(max_length=200, verbose_name='Event Speaker')
    event_status = models.CharField(max_length=16, verbose_name='Status', default="PENDING")
    event_datecreated = models.DateTimeField(default=now)
    event_dateupdated = models.DateTimeField(default=now)

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width = "50" height="50" />'%(self.event_image))

    def __str__(self):
        return self.event_id

GFMICsystem/users/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponse
from .models import Membership, Event
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from datetime import datetime, date
import random
from django.core.files.storage import FileSystemStorage
from django.core.files.base import ContentFile
from django.views.decorators.csrf import csrf_exempt
import base64
from django.db.models import Q
import json

today = datetime.today()

def home(request):
    request.session['session_user_id'] = None
    request.session['session_user_sub'] = None
    request.session['session_user_status'] = None
    request.session['session_fname'] = None
    request.session['seesion_lname'] = None
    return render(request, 'home.html')

def login(request):
    request.session['session_user_id'] = None
    request.session['session_user_sub'] = None
    request.session['session_user_status'] = None
    request.session['session_fname'] = None
    request.session['seesion_lname'] = None
    return render(request, 'login.html')

def logout(request):
    request.session['session_user_id'] = None
    request.session['session_user_sub'] = None
    request.session['session_user_status'] = None
    request.session['session_fname'] = None
    request.session['seesion_lname'] = None
    return render(request, 'login.html')

def forgot_pass(request):
    return render(request, 'forgot_password.html')

def error_404(request):
    return render(request, '404.html')

def about(request):
    return render(request, 'about.html')

def home_event(request):
    return render(request, 'home_event.html')

def membership_conference(request):
    return render(request, 'membership-conference.html')

def national_convention(request):
    return render(request, 'national-convention.html')

def webinar(request):
    return render(request, 'webinar.html')

def faqs(request):
    return render(request, 'faqs.html')

def process_login(request):
    email = request.POST.get('useremail')
    password = request.POST.get('password')
    try:
        m = Membership.objects.get(user_email=email, user_password=password)
        request.session['session_user_id'] = m.user_id
        request.session['session_user_sub'] = m.user_sub
        request.session['session_user_status'] = m.user_status
        request.session['session_fname'] = m.user_fname
        request.session['seesion_lname'] = m.user_lname
        request.session['session_user_file'] = json.dumps(str(m.user_file))
        return HttpResponseRedirect('/dashboard', {'member': m})
        # return render(request, 'dashboard.html', {
        #     'member': m
        # })
    except ObjectDoesNotExist:
        return render(request, 'login.html', {
            'error_message': 'Either email or password are incorrect :'
        })

def dashboard(request):
    if request.session['session_user_id']:
        m = Membership.objects.get(user_id=request.session['session_user_id'])
        request.session['session_user_sub'] = m.user_sub
    return render(request, 'dashboard.html')

def upload_profile(request):
    user_id = request.POST.get('userid')
    return render(request, 'dashboard.html')

def profile(request):
    user_id = request.POST.get('user_id')
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    middle_name = request.POST.get('middle_name')
    contact = request.POST.get('contact')
    address = request.POST.get('address')
    agency = request.POST.get('agency')
    college = request.POST.get('college')
    post_grad = request.POST.get('post_grad')
    try:
        m = Membership.objects.get(user_id=user_id)
        m.user_fname = first_name
        m.user_mname = middle_name
        m.user_lname = last_name
        m.user_mobile = contact
        m.user_address = address
        m.user_agency = agency
        m.user_post = post_grad
        m.user_school = college
        m.save()
        request.session['session_fname'] = m.user_fname
        request.session['seesion_lname'] = m.user_lname
        data = {'success':True}
        return JsonResponse(data, safe=False)
    except ObjectDoesNotExist:
        data = {'error':True}
        return JsonResponse(data, safe=False)

def register(request):
    return render(request, 'register.html')

def register_account(request):
    email = request.POST.get('useremail')
    password = request.POST.get('password')
    password1 = request.POST.get('password1')
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr =''.join((random.choice(chars)) for x in range(5))
    user_no = 'MN-' + randomstr
    if email != None or password != None or password1 != None:
        if password == password1:
            try:
                m = Membership.objects.get(user_email=email)
                return render(request, 'register.html', {
                    'error_message': 'Duplicated email :' + email
                })
            except ObjectDoesNotExist:
                m = Membership.objects.create(user_email=email, user_password=password, user_no=user_no)
                m.save()
                return HttpResponseRedirect('/login')
        else:
            return render(request, 'register.html', {
                'error_message': 'Password does not match.' 
            })
    else:
        return render(request, 'register.html', {
            'error_message': 'Please fill up the required fields.'
        })
        

def membership(request):
    try:
        if request.session['session_user_sub'] == 'ADMIN':
            member_list = Membership.objects.filter(~Q(user_sub='ADMIN')).order_by('-user_dateupdated')
            context = {'member_list': member_list}
            return render(request, 'membership.html', context)
        else:
            member_list = Membership.objects.filter(~Q(user_sub='ASSOCIATE')).order_by('-user_dateupdated')
            context = {'member_list': member_list}
            return render(request, 'membership.html', context)
    except ObjectDoesNotExist:
        return render(request, 'membership.html')

def add_membership(request):
    m_no = request.POST.get('m_no')
    m_name = request.POST.get('m_name')
    m_mobile = request.POST.get('m_mobile')
    m_satus = request.POST.get('m_satus')
    m_sub = request.POST.get('m_sub')
    email = request.POST.get('email')
    pass1 = request.POST.get('pass')
    try:
        c = Membership.objects.get(user_email=email)
        data = {'error': True}
        return JsonResponse(data, safe=False)
    except ObjectDoesNotExist:
        member = Membership(
            user_no=m_no,
            user_email=email,
            user_password=pass1,
            user_sub=m_sub,
            user_status = m_satus,
            user_fname = m_name,
            user_mobile = m_mobile
        )
        member.save()
        data = {'success': True}
        return JsonResponse(data, safe=False)

# def edit_account(request):
#     acc_id = request.POST.get('acc_id') 
#     account_sub = request.POST.get('account_sub')
#     try:
#         c = Account.objects.get(account_id=acc_id)
#         c.account_subscription = account_sub
#         c.account_dateupdated = today
#         c.save()
#         data = {'success': True}
#         return JsonResponse(data, safe=False)
#     except ObjectDoesNotExist:
#         data = {'error': True}
#         return JsonResponse(data, safe=False)

def view_membership(request):
    user_id = request.POST.get('user_id')
    print(user_id)
    try:
        a = Membership.objects.get(user_id=user_id)
        data = {
            'member_proof': str(a.user_file),
            'membership_no':a.user_no,
            'payment_amount':a.user_amount,
            'mode_of_payment':a.user_pmode,
            'm_start':a.user_validity,
            'm_end':a.user_expire,
            'm_status':a.user_status,
        }
        print(a.user_file)
        return JsonResponse(data, safe=False)
    except ObjectDoesNotExist:
        data = {'error':True}
        return JsonResponse(data, safe=False)

# def delete_account(request):
#     acc_id = request.POST.get('acc_id') 
#     try:
#         c = Account.objects.get(account_id=acc_id)
#         if c.account_status == 'ACTIVE':
#             c.account_status = 'INACTIVE'
#         else:
#             c.account_status = 'ACTIVE'
#             c.account_dateupdated = today
#         c.account_dateupdated = today
#         c.save()
#         data = {'success': True}
#         return JsonResponse(data, safe=False)
#     except ObjectDoesNotExist:
#         data = {'error': True}
#         return JsonResponse(data, safe=False)
   
def payment(request):
    userid = request.POST.get('payment_id')
    img = request.FILES.get("file")
    mode_of_payment = request.POST.get('mode_of_payment')
    m_start = request.POST.get('m_start')
    if m_start:
        # m_start = m_start + ' ' + '00:00:00'
        mstart = datetime.strptime(m_start, "%d/%m/%Y").strftime('%Y-%m-%d %H:%M:%S')
    
        # m_start = datetime.strftime(m_start, "%Y-%m-%d %H:%M:%S")
    
        # m_start = datetime.strptime(m_start, "YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]")
        print(m_start)
        
        m_end = request.POST.get('m_end')
        mend = datetime.strptime(m_start, "%d/%m/%Y").strftime('%Y-%m-%d %H:%M:%S')
    payment_amount = request.POST.get('payment_amount')
  
    try: 
        m = Membership.objects.get(user_id=userid)
        m.user_amount = payment_amount
        m.user_pmode = mode_of_payment
        m.user_validity = mstart
        m.user_expire = mend
        m.user_file = img
        m.save()
        request.session['session_user_sub'] = m.user_sub
        return HttpResponseRedirect('dashboard')
    except ObjectDoesNotExist:
        return HttpResponseRedirect('dashboard', {
            'error_message': 'failed'
        })

def approve_membership(request):

GFMICsystem/users/templates/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-landing navbar-light fixed-top" id="navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'users:home' %}">
            <img src="{% static 'assets/images/logos/black logo.png' %}" class="card-logo card-logo-dark" alt="logo dark" height="60">
            <img src="{% static 'assets/images/logos/white logo.png' %}" class="card-logo card-logo-light" alt="logo light" height="60">
        </a>
        <button class="navbar-toggler py-0 fs-20 text-body" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="mdi mdi-menu"></i>
        </button>   

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mt-2 mt-lg-0" id="navbar-example">
                <li class="nav-item">
                    <a class="nav-link fs-14 active" href="#home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-14" href="#aboutus">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-14" href="#membership">Membership</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-14" href="#events">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-14" href="#news">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-14" href="#faqs">FAQs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-14" href="#contact">Contact Us</a>
                </li>
            </ul>

            <div class="">
                <a href="{% url 'users:login' %}" class="btn btn-link fw-medium mx-auto">Sign In</a>
                <a href="{% url 'users:register' %}" class="btn btn-primary">Sign Up</a>
            </div>
        </div>

    </div>
</nav>
<div class="bg-overlay bg-overlay-pattern"></div>   
<!-- end navbar -->

GFMICsystem/users/templates/home_footer.html
{% load static %}
<!-- Start footer -->
<footer class="custom-footer bg-dark py-5 position-relative">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mt-4">
                <div>
                    <div>
                        <img src="{% static 'assets/images/logos/white logo.png' %}" alt="logo light" height="60">
                    </div>
                    <div class="mt-4 fs-13">
                        <p style="text-align:justify">"Working globally with governments, organizations, and individuals, the International Consortium on Governmental Financial Management, Inc. 
                        is dedicated to improving financial management, so governments can better serve their citizens."  </p>
                    
                    </div>
                </div>
            </div>

            <div class="col-lg-7 ms-lg-auto">
                <div class="row">
                    <div class="col-sm-4 mt-4">
                        <h5 class="text-white mb-0">Company</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list fs-14">
                                <li><a href="{% url 'users:about' %}">About Us</a></li>
                                <li><a href="pages-gallery.html">Membership</a></li>
                                <li><a href="{% url 'users:event' %}">Events</a></li>
                                <li><a href="pages-timeline.html">News</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-4 mt-4">
                        <h5 class="text-white mb-0">Discover</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list fs-14">
                                <li><a href="pages-pricing.html">Webinars</a></li>
                                <li><a href="https://www.google.com/maps/place/The+One+Executive+Building,
                            +5+West+Ave,+Quezon+City,+Metro+Manila,+Philippines/@14.637727,121.024846,
                            10z/data=!4m5!3m4!1s0x3397b65107c0e407:0xef78051484f3ac00!8m2!3d14.6377267!4d121.0248458?hl=en-US">Location</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-4 mt-4">
                        <h5 class="text-white mb-0">Support</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list fs-14">
                                <li><a href="{% url 'users:faqs' %}">FAQ</a></li>
                                <li><a href="pages-faqs.html">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="row text-center text-sm-start align-items-center mt-5">
            <div class="col-sm-6">

                <div>
                    <p class="copy-rights mb-0">
                        <script>document.write(new Date().getFullYear())</script> © GFMIC, INC.
                    </p>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end mt-3 mt-sm-0">
                    <ul class="list-inline mb-0 footer-social-link">
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/gfmic.inc" class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-facebook-fill"></i>
                                </div>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.google.com/maps/place/The+One+Executive+Building,
                            +5+West+Ave,+Quezon+City,+Metro+Manila,+Philippines/@14.637727,121.024846,
                            10z/data=!4m5!3m4!1s0x3397b65107c0e407:0xef78051484f3ac00!8m2!3d14.6377267!4d121.0248458?hl=en-US"
                                class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-google-fill"></i>
                                </div>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://twitter.com/icgfm"
                                class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-twitter-fill"></i>
                                </div>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.instagram.com/icgfm/"
                                class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-instagram-fill"></i>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end footer -->

GFMICsystem/users/templates/sidebar.html
  <!-- ========== App Menu ========== -->
        <div class="app-menu navbar-menu">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <!-- Dark Logo-->
                <a href="dashboard.html" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="../assets/images/logos/gfmic logo.png" alt="" height="50">
                    </span>
                    <span class="logo-lg">
                        <img src="../assets/images/logos/black logo.png" alt="" height="50">
                    </span>
                </a>
                <a href="dashboard.html" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="../assets/images/logos/gfmic logo.png" alt="" height="50">
                    </span>
                    <span class="logo-lg">
                        <img src="../assets/images/logos/white logo.png" alt="" height="50">
                    </span>
                </a>
                <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
                    <i class="ri-record-circle-line"></i>
                </button>
            </div>

            <div id="scrollbar">
                <div class="container-fluid">

                    <div id="two-column-menu">
                    </div>
                    <ul class="navbar-nav" id="navbar-nav">
                        <li class="menu-title"><span data-key="t-menu">Menu</span></li>
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="{% url 'users:dashboard' %}" role="button" aria-expanded="false" aria-controls="sidebarDashboards">
                                <i data-feather="home" class="icon-dual"></i> <span data-key="t-dashboards">Dashboard</span>
                            </a>
                        </li> <!-- end Dashboard Menu -->
                        {% if  request.session.session_user_sub == 'ASSOCIATE' or request.session.session_user_sub  == 'ADMIN' %}
                        <li class="nav-item">
                            <a class="nav-link menu-link" data-bs-toggle="collapse" href="" role="button" aria-expanded="false" aria-controls="Events">
                                <i data-feather="grid" class="icon-dual"></i> <span data-key="t-apps">Events</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarEmail">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{%  url 'users:events' %}" class="nav-link" role="button" aria-expanded="false" aria-controls="Events" data-key="t-email-templates">
                                            Event List <span class="badge badge-pill bg-danger" data-key="t-new"></span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{%  url 'users:event' %}" class="nav-link" role="button" aria-expanded="false" aria-controls="Events" data-key="t-email-templates">
                                            Events <span class="badge badge-pill bg-danger" data-key="t-new"></span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="event-registration.html" class="nav-link" role="button" aria-expanded="false" aria-controls="Registration" data-key="t-email-templates">
                                            User Registration <span class="badge badge-pill bg-danger" data-key="t-new"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{%  url 'users:events' %}" class="nav-link" role="button" aria-expanded="false" aria-controls="Events" data-key="t-email-templates"> <i data-feather="grid" class="icon-dual"></i>
                                Events <span class="badge badge-pill bg-danger" data-key="t-new"></span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="ecert.html" role="button" aria-expanded="false" aria-controls="sidebarApps">
                                <i data-feather="grid" class="icon-dual"></i> <span data-key="t-apps">eCertificates</span>
                            </a>
                        </li>
                        {% if  request.session.session_user_sub == 'ASSOCIATE' or request.session.session_user_sub  == 'ADMIN' %}
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="{% url 'users:membership' %}"  role="button" aria-expanded="false" aria-controls="sidebarLayouts">
                                <i data-feather="layout" class="icon-dual"></i> <span data-key="t-layouts">Membership</span>
                            </a>
                        </li> <!-- end Dashboard Menu -->
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarPages"  role="button" aria-expanded="false" aria-controls="sidebarPages">
                                <i data-feather="command" class="icon-dual"></i> <span data-key="t-pages">BitBo Academy</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link menu-link" href="or.html"  role="button" aria-expanded="false" aria-controls="sidebarLanding">
                                <i class="ri-rocket-line"></i> <span data-key="t-landing">OR Management</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarAdvanceUI"  role="button" aria-expanded="false" aria-controls="sidebarAdvanceUI">
                                <i data-feather="layers" class="icon-dual"></i> <span data-key="t-advance-ui">Help Desk</span>
                            </a>
                        </li>

                    </ul>
                </div>
                <!-- Sidebar -->
            </div>

            <div class="sidebar-background"></div>
        </div>
        <!-- Left Sidebar End -->
        <!-- Vertical Overlay-->
        <div class="vertical-overlay"></div>